services:
  app:
    build:
      dockerfile_inline: |
        FROM ruby:2.7-bullseye
        COPY Gemfile Gemfile.lock tabled.gemspec .
        RUN bundle install
    working_dir: /app
    volumes:
      - ./:/app
